#ifndef __REQUESTS_H_INCLUDED__
#define __REQUESTS_H_INCLUDED__

#define CUSTOM_RQ_SET_CURRENT_LED	0
#define CUSTOM_RQ_SET_COLOR_R    	1
#define CUSTOM_RQ_SET_COLOR_G    	2
#define CUSTOM_RQ_SET_COLOR_B    	3
#define CUSTOM_RQ_WRITE_TO_LEDS   4
#define CUSTOM_RQ_SET_LEDCOUNT    10
#define CUSTOM_RQ_GET_LEDCOUNT    20

#endif /* __REQUESTS_H_INCLUDED__ */
